apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolldice
  namespace: rolldice
spec:
  selector:
    matchLabels:
      app: rolldice
  template:
    metadata:
      labels:
        app: rolldice
    spec:
      containers:
      - name: rolldice
        image: dockerdaemon0901/rolldice:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://jaeger-collector.opentelemetry.svc.cluster.local:4318"
        